spring:
  application:
    name: EurekaClient

server:
  port: 9191

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/         #Eureka Server 경로
  instance:
    hostname: localhost
